# Generated by Django 5.2.4 on 2025-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название объявления')),
                ('region', models.CharField(choices=[('Винницкая', 'Винницкая'), ('Волынская', 'Волынская'), ('Днепропетровская', 'Днепропетровская'), ('Донецкая', 'Донецкая'), ('Житомирская', 'Житомирская'), ('Закарпатская', 'Закарпатская'), ('Запорожская', 'Запорожская'), ('Ивано-Франковская', 'Ивано-Франковская'), ('Киевская', 'Киевская'), ('Кировоградская', 'Кировоградская'), ('Луганская', 'Луганская'), ('Львовская', 'Львовская'), ('Николаевская', 'Николаевская'), ('Одесская', 'Одесская'), ('Полтавская', 'Полтавская'), ('Ровненская', 'Ровненская'), ('Сумская', 'Сумская'), ('Тернопольская', 'Тернопольская'), ('Харьковская', 'Харьковская'), ('Херсонская', 'Херсонская'), ('Хмельницкая', 'Хмельницкая'), ('Черкасская', 'Черкасская'), ('Черниговская', 'Черниговская'), ('Черновицкая', 'Черновицкая'), ('г. Киев', 'г. Киев'), ('г. Севастополь', 'г. Севастополь'), ('АР Крым', 'АР Крым')], max_length=100, verbose_name='Регион')),
                ('marka', models.CharField(choices=[('Toyota', 'Toyota'), ('BMW', 'BMW'), ('Audi', 'Audi'), ('Mercedes', 'Mercedes')], max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ($)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
